# Generated by Django 5.2.1 on 2026-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgparecord',
            name='semesters',
            field=models.JSONField(default=list),
        ),
    ]
