# Generated by Django 5.2.1 on 2026-05-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0002_cgparecord_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgparecord',
            name='semesters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
