# Generated by Django 5.2.1 on 2026-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0005_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
    ]
