# Generated by Django 5.2.1 on 2026-05-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0006_alter_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
    ]
