# Generated by Django 5.2.1 on 2026-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0008_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Video Editing', 'Video Editing'), ('Graphics Design', 'Graphics Design'), ('Cybersecurity', 'Cybersecurity'), ('Marketing', 'Marketing')], max_length=100),
        ),
    ]
