# Generated by Django 5.2.1 on 2026-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0009_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='advisor',
            field=models.CharField(default='Ichason', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default='$0', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
