# Generated by Django 5.2.1 on 2026-06-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0011_timetableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
