# Generated by Django 5.2.1 on 2026-06-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0018_paidtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwallet',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
