# Generated by Django 5.2.1 on 2026-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0019_aiwallet_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='NGN', max_length=5),
        ),
    ]
