# Generated by Django 5.2.1 on 2026-06-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0020_profile_country_profile_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
