# Generated by Django 5.2.1 on 2026-06-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0022_aisemanticcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisemanticcache',
            name='user',
        ),
        migrations.AddField(
            model_name='aisemanticcache',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
