# Generated by Django 5.2.1 on 2026-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0025_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgparecord',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
