# Generated by Django 5.2.1 on 2026-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0026_cgparecord_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgparecord',
            name='classification',
            field=models.CharField(max_length=50),
        ),
    ]
